# Generated by Django 5.2 on 2025-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
