# Generated by Django 5.2 on 2025-07-03 12:25

from django.db import migrations
from django.utils.text import slugify


def populate_tag_slugs(apps, schema_editor):
    PostTag = apps.get_model('posts', 'PostTag')
    for tag in PostTag.objects.all():
        if not tag.slug:
            tag.slug = slugify(tag.name, allow_unicode=True)
            tag.save()


def reverse_populate_tag_slugs(apps, schema_editor):
    PostTag = apps.get_model('posts', 'PostTag')
    for tag in PostTag.objects.all():
        tag.slug = None
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posttag_slug'),
    ]

    operations = [
        migrations.RunPython(populate_tag_slugs, reverse_populate_tag_slugs),
    ]
