# Generated by Django 5.2 on 2025-07-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20250703_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
